#!/usr/bin/expect

set timeout 20

set ip_addr [lindex $argv 0]
set dir [lindex $argv 1]
set flag [lindex $argv 2]

if { "$flag" == "0" } {
    spawn scp root@$ip_addr:/etc/config/cgminer ./$dir
} elseif { "$flag" == "1" }  {
    spawn scp ./$dir/cgminer root@$ip_addr:/etc/config
} elseif { "$flag" == "2" } {
    spawn scp root@$ip_addr:/root/CGMiner_Power.log ./$dir
} else {
    exit
}

expect "password:"
send "1\r"

expect {
    \"Permission denied, please try again.\" exit
}
