#!/usr/bin/expect

set timeout 20

set ip_addr [lindex $argv 0]
set flag [lindex $argv 1]

if { "$flag" == "0" } {
    spawn scp root@$ip_addr:/etc/config/cgminer ./
} elseif { "$flag" == "1" }  {
    spawn scp ./cgminer root@$ip_addr:/etc/config
} elseif { "$flag" == "2" } {
    spawn scp root@$ip_addr:/root/CGMiner_Power.log ./
} else {
    exit
}

expect "password:"
send "1\r"

expect {
    \"Permission denied, please try again.\" exit
}
